"""Short teaching cards grounded in the 46-slide course deck."""
PARTS = {
    1: ('Understanding Word Structure', 'Word Structure', '#2463eb', 'What is inside a word?', '3–9'),
    2: ('Understanding Word Forms', 'Word Forms', '#14805e', 'Are all word changes doing the same job?', '10–17'),
    3: ('Processing Word Forms by Computer', 'Computer Processing', '#b56a09', 'Which paths can a word machine follow?', '18–28'),
    4: ('Finding Information in Sentences', 'Sentence Information', '#d63e65', 'Who, which organization, where, and when?', '29–36'),
    5: ('Making Better NLP Decisions', 'NLP Decisions', '#7950c9', 'What evidence helps us choose a label?', '37–46'),
}

# part, concept, discussion question, think prompt, example, explanation
ROWS = [
 (1, 'Morphology', 'Are happy, unhappy, happiness, and unhappiness connected?', 'Find the shared meaning before looking at their letters.', 'unhappiness → un + happy + ness', 'Morphology studies the internal structure and formation of words. Different character strings can have related meanings.'),
 (1, 'Morpheme', 'What information does s add to books?', 'Try removing the final piece. What changes?', 'books → book + s; cats → cat + s; played → play + ed', 'A morpheme is the smallest unit carrying meaning or grammatical information. book supplies meaning; -s supplies plural information.'),
 (1, 'Root, prefix, and suffix', 'Where are the meaningful pieces in unhelpful?', 'Look before and after the central meaning.', 'un | help | ful; replayed → re + play + ed; careless → care + less', 'The root carries the central meaning. A prefix comes before it and a suffix after it. Some words have several suffixes.'),
 (1, 'Why morphology matters', 'Would an exact search for play find playing?', 'Imagine searching play football in a document containing Sara is playing football.', 'play ≠ playing as character strings; playing → play + ing', 'Recognizing related forms helps search, translation, text analysis, summarization, chatbots, spelling and grammar tools, and multilingual NLP.'),
 (2, 'Inflection', 'Does played name a new action, or a form of play?', 'Compare a grammatical change with a new dictionary word.', 'play → plays → played → playing; book → books; walk → walked', 'Inflection changes grammatical form without creating a new lexical item. plays is third-person singular present; books is plural.'),
 (2, 'Derivation', 'Is a teacher the same kind of thing as teach?', 'Name the grammatical category before and after.', 'teach → teacher (verb → noun); happy → happiness (adjective → noun); care → careless; use → useful; create → creation', 'Derivation creates a new related word and may change grammatical category. It need not always change category: happy → unhappy remains an adjective.'),
 (2, 'Morphological diversity', 'Can English word rules work unchanged in every language?', 'Compare adding an ending with changing the inside of a word.', 'English book → books; Arabic kitāb → kutub; German Buch → Bücher; Turkish ev → evler', 'Languages express number, gender, case, person, and tense in different ways. Multilingual NLP needs language-appropriate patterns.'),
 (2, 'Morphological paradigm', 'Must a computer memorize play, played, and playing as unrelated strings?', 'Organize the forms by their grammatical jobs.', 'play / plays / played / playing; walk / walks / walked / walking', 'A morphological paradigm is an organized set of related grammatical forms of a word. It exposes systematic relationships.'),
 (2, 'Regular and irregular forms', 'talk → talked, work → worked, but go → what?', 'Predict a form, then ask whether your rule always works.', 'talk → talking; work → worked; go → went', 'Language has regular patterns and irregular forms. A simple add-ed rule overgeneralizes to goed. Lexical information or richer learning is needed.'),
 (3, 'Finite-State Machine', 'Can our word machine accept play + xyz?', 'Trace only allowed arrows from the start to a final state.', 'START → play → ed → FINAL; play + xyz is rejected', 'An FSM has a finite set of states and allowed transitions. A state represents a stage; a transition is a permitted move. Reaching a final state accepts the input.'),
 (3, 'Finite-State Morphology', 'What changes when our state machine works specifically with words?', 'Connect a general computational tool to an NLP task.', 'play + s → plays; play + ed → played; play + ing → playing', 'Finite-state morphology applies finite-state methods to word analysis and generation. Appropriate lexical rules can handle irregulars too.'),
 (3, 'Morphological analysis', 'When we receive books and return book + s, which direction are we going?', 'Start with a complete word and uncover its information.', 'played → root play, suffix ed, past form; playing → play + ing; cars → car + s', 'Analysis maps WORD → INFORMATION: possible root, affixes, and grammatical information. A word may allow more than one analysis.'),
 (3, 'Morphological generation', 'When we receive walk + ed, what must the computer build?', 'Start with pieces or grammatical features.', 'walk + ed → walked; teach + er → teacher; happy + ness → happiness', 'Generation maps INFORMATION → WORD. It may need spelling rules as well as concatenation.'),
 (3, 'Automatic morphology learning', 'What repeats in play/played/playing and walk/walked/walking?', 'Compare many examples rather than writing a rule first.', 'play → played; walk → walked; talk → talked; work → worked; then jump → jumped', 'Automatic morphology learning discovers useful word patterns from data. Repeated -ed and -ing endings are clues. A small sample does not establish a universal rule.'),
 (3, 'Rule-based vs automatic learning', 'Would you want to write thousands of rules for every language?', 'Who supplies the pattern: the human or the data?', 'Human gives rules → computer applies them. Human gives examples → computer discovers patterns.', 'Rule-based systems use explicit human rules. Learning systems infer patterns from examples. Both can fail when their rules or data miss important cases.'),
 (4, 'Shallow parsing / chunking', 'Which words belong together in the smart student completed the difficult project?', 'Group useful phrases without building a complete grammar tree.', '[The smart student] NP → [completed] VP → [the difficult project] NP', 'Shallow parsing, or chunking, identifies useful groups without a complete deep grammatical analysis. A noun phrase acts as a noun; a verb phrase is centered on a verb.'),
 (4, 'Named Entity Recognition', 'Can we extract who, which organization, where, and when?', 'Look for named real-world information rather than ordinary phrases.', 'Dr. Sara joined Microsoft in Dubai on Monday. Sara: PERSON; Microsoft: ORGANIZATION; Dubai: LOCATION; Monday: DATE.', 'NER identifies and classifies named entities. It converts text into structured information useful for search, question answering, and organizing large collections such as 10,000 news articles.'),
 (4, 'O and entity sequences', 'In Ahmed works at ABC Bank in Dubai, is every token an entity?', 'What label should ordinary connecting words receive?', 'Ahmed/PER works/O at/O ABC/ORG Bank/ORG in/O Dubai/LOC', 'O means outside any named entity in the chosen annotation scheme. Multiword names may span several tokens. PER, ORG, and LOC abbreviate the full category names.'),
 (4, 'Context and ambiguity', 'Jordan: person or location?', 'Ask for the surrounding sentence before deciding.', 'I travelled to Jordan. / Jordan submitted the assignment. Apple opened a new office. / I ate an apple.', 'Context changes interpretation. Jordan can name a country or a person; Apple can name an organization while apple can be ordinary fruit.'),
 (4, 'Chunking vs NER', 'Does finding a noun phrase tell us it is a named person?', 'Compare the questions each task answers.', 'the smart student → NP; Sara → PERSON', 'Chunking asks which words belong together. NER asks which named things appear and what their categories are. The tasks are related but solve different problems.'),
 (5, 'Limits of simple rules', 'Why does capitalized word → PERSON fail?', 'Test the same rule on a person, a place, and a company.', 'Ahmed arrived. ✓ Dubai is beautiful. ✗ Microsoft released a product. ✗', 'Capitalization alone cannot identify entity type. The model needs more evidence.'),
 (5, 'Features', 'What clues help label Dubai in Sara travelled to Dubai?', 'Inspect the word, its neighbors, and its shape.', 'Current word: Dubai; previous: to; capitalized: yes; nearby: travelled. For Microsoft, works at is another clue.', 'Features are useful input information for a decision. Current, previous, next, nearby words, and word shape can all help. No single clue guarantees the answer.'),
 (5, 'Maximum Entropy model', 'How could a model combine several clues?', 'Think about uncertainty over possible labels.', 'She lives in Dubai. Illustrative probabilities: Person 0.05, Organization 0.05, Location 0.90.', 'A Maximum Entropy classifier combines weighted features to estimate probabilities for labels. In this lesson, editable probabilities are an educational simulation, not a trained model.'),
 (5, 'Argmax', 'Which label wins with probabilities 0.05, 0.05, and 0.90?', 'Choose the label with the greatest value.', 'Person 0.05; Organization 0.05; Location 0.90 → LOCATION', 'Argmax returns the label with the highest probability. It chooses a label, not the numerical probability itself. High confidence does not guarantee correctness.'),
 (5, 'Random fields', 'Can labels have relationships with other labels?', 'Imagine variables connected to their neighbors.', 'New ↔ York ↔ University', 'A random field models relationships among variables. In a sequence, relationships can connect neighboring label variables.'),
 (5, 'CRF and sequence labeling', 'Should New, York, and University be labeled independently?', 'Consider whether these words name one organization together.', 'Ahmed/PER works/O at/O New/ORG York/ORG University/ORG', 'A Conditional Random Field models a label sequence conditioned on the observed input. A linear-chain CRF combines input features and neighboring label relationships to select a sequence jointly.'),
 (5, 'Maximum Entropy vs CRF', 'When do we need one label, and when do we need a consistent sequence?', 'Compare a single Dubai decision with a multiword organization.', 'Maximum Entropy: features → probabilities → one label. CRF: features + neighboring labels → label sequence.', 'The standalone Maximum Entropy classifier here makes a local decision. CRF accounts for label dependencies across a sequence. It does not simply copy the previous label, and it does not guarantee correct output.'),
]
CONCEPTS = [dict(part=p, name=n, question=q, think=t, example=e, explanation=c) for p,n,q,t,e,c in ROWS]

CODING_TASKS = {
 1: 'Create a simple Python Streamlit app called Word X-Ray. Accept an English word. Use a small predefined set of prefixes and suffixes to display its possible prefix, root, and suffix visually. Explain what each part adds.',
 2: 'Extend the SAME Word X-Ray app. Preserve Part 1. Add inflection/derivation classification and a Word Family section. Explain the new code separately. Test played, books, teacher, happiness, playing, and go.',
 3: 'Extend the SAME app with Morphological Analysis and Generation modes. Generate base, third-person singular, past, ing-form, and noun plural when appropriate. Test played, playing, books, play + past, play + ing, book + plural. Then try went and go + past. Explain why a simple suffix rule fails.',
 4: 'Extend the SAME app with a Sentence Analyzer for chunking and NER (Person, Organization, Location, Date). Explain which function performs each task. Test Sara joined Microsoft in Dubai on Monday; Apple opened a new office; I ate an apple.',
 5: 'Extend the SAME Sentence Analyzer to show features for a selected token, illustrative Person/Organization/Location probabilities, the argmax label, and a token-label sequence. Clearly label the probabilities as an educational simulation, not a real NER model output.',
}
